// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtphOLsogNIGcJDkM1CLLaJ-sQYhgWTBA',
    appId: '1:930008774211:web:ccab02cf872a65a7dd46f6',
    messagingSenderId: '930008774211',
    projectId: 'better-tok',
    authDomain: 'better-tok.firebaseapp.com',
    databaseURL: 'https://better-tok-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'better-tok.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsUa3mK7Yvcya2z083ILmwoSJKAgP69xc',
    appId: '1:930008774211:android:becbdbf21e9f266ddd46f6',
    messagingSenderId: '930008774211',
    projectId: 'better-tok',
    databaseURL: 'https://better-tok-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'better-tok.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACzXX7NwYHN3nCjvcVuiKVyHI8QlRe1nY',
    appId: '1:930008774211:ios:93d87f0b4e673f98dd46f6',
    messagingSenderId: '930008774211',
    projectId: 'better-tok',
    databaseURL: 'https://better-tok-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'better-tok.appspot.com',
    iosClientId: '930008774211-qatki1h0ap570b0vb4s1krtqbqkca4sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACzXX7NwYHN3nCjvcVuiKVyHI8QlRe1nY',
    appId: '1:930008774211:ios:586e9037ac68277bdd46f6',
    messagingSenderId: '930008774211',
    projectId: 'better-tok',
    databaseURL: 'https://better-tok-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'better-tok.appspot.com',
    iosClientId: '930008774211-dmm3kf25cqpb44lmr0f1i8do0vbs7qm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone.RunnerTests',
  );
}
